<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="6" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-13T14:01:15 PST" name="RetryFailedTestSuite" finished-at="2023-12-13T14:02:47 PST" duration-ms="91861">
    <groups>
    </groups>
    <test started-at="2023-12-13T14:01:15 PST" name="RetryMultipleFailedTestCases" finished-at="2023-12-13T14:02:47 PST" duration-ms="91861">
      <class name="com.amazon.testngFrameworl.MainPage_AllTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:01:16 PST" name="setUp" finished-at="2023-12-13T14:01:22 PST" duration-ms="6086" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="all_BEstSellersTest()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:01:22 PST" name="all_BEstSellersTest" finished-at="2023-12-13T14:01:29 PST" duration-ms="7821" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- all_BEstSellersTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:01:29 PST" name="tearDown" finished-at="2023-12-13T14:01:30 PST" duration-ms="1054" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:01:30 PST" name="setUp" finished-at="2023-12-13T14:01:36 PST" duration-ms="5893" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="clickAll()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:01:36 PST" name="clickAll" finished-at="2023-12-13T14:01:45 PST" duration-ms="8567" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [MAIN MENUu] but found [MAIN MENU]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [MAIN MENUu] but found [MAIN MENU]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.amazon.testngFrameworl.MainPage_AllTest.clickAll(MainPage_AllTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickAll -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:01:45 PST" name="tearDown" finished-at="2023-12-13T14:01:46 PST" duration-ms="1143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:01:46 PST" name="setUp" finished-at="2023-12-13T14:01:51 PST" duration-ms="5241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="clickAll()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:01:51 PST" name="clickAll" finished-at="2023-12-13T14:02:00 PST" duration-ms="8675" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [MAIN MENUu] but found [MAIN MENU]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [MAIN MENUu] but found [MAIN MENU]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.amazon.testngFrameworl.MainPage_AllTest.clickAll(MainPage_AllTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickAll -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:02:00 PST" name="tearDown" finished-at="2023-12-13T14:02:01 PST" duration-ms="800" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:02:01 PST" name="setUp" finished-at="2023-12-13T14:02:11 PST" duration-ms="9729" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="clickAll()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:02:11 PST" name="clickAll" finished-at="2023-12-13T14:02:19 PST" duration-ms="8605" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [MAIN MENUu] but found [MAIN MENU]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [MAIN MENUu] but found [MAIN MENU]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.amazon.testngFrameworl.MainPage_AllTest.clickAll(MainPage_AllTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickAll -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:02:19 PST" name="tearDown" finished-at="2023-12-13T14:02:20 PST" duration-ms="785" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:02:20 PST" name="setUp" finished-at="2023-12-13T14:02:27 PST" duration-ms="6909" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="clickAll()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:02:27 PST" name="clickAll" finished-at="2023-12-13T14:02:36 PST" duration-ms="8681" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [MAIN MENUu] but found [MAIN MENU]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [MAIN MENUu] but found [MAIN MENU]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.amazon.testngFrameworl.MainPage_AllTest.clickAll(MainPage_AllTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickAll -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:02:36 PST" name="tearDown" finished-at="2023-12-13T14:02:36 PST" duration-ms="889" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:02:36 PST" name="setUp" finished-at="2023-12-13T14:02:42 PST" duration-ms="5457" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="searchTest()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:02:42 PST" name="searchTest" finished-at="2023-12-13T14:02:47 PST" duration-ms="4667" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amazon.testngFrameworl.MainPage_AllTest@2805d709]" started-at="2023-12-13T14:02:47 PST" name="tearDown" finished-at="2023-12-13T14:02:47 PST" duration-ms="782" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.amazon.testngFrameworl.MainPage_AllTest -->
    </test> <!-- RetryMultipleFailedTestCases -->
  </suite> <!-- RetryFailedTestSuite -->
</testng-results>
